import type { CollectionConfig } from 'payload'
import { adminOnly, adminOrAnalyst } from '@/access/roles'

export const Funds: CollectionConfig = {
  slug: 'funds',
  admin: {
    defaultColumns: ['name', 'vintage', 'size', 'status', 'manager'],
    useAsTitle: 'name',
  },
  access: {
    read: adminOrAnalyst,
    create: adminOrAnalyst,
    update: adminOrAnalyst,
    delete: adminOnly,
  },
  fields: [
    { name: 'name', type: 'text', required: true },
    { name: 'vintage', type: 'text', required: true },
    { name: 'size', type: 'number', required: true },
    { name: 'committedCapital', type: 'number', required: true },
    { name: 'calledCapital', type: 'number', defaultValue: 0 },
    { name: 'distributedCapital', type: 'number', defaultValue: 0 },
    { name: 'netAssetValue', type: 'number', defaultValue: 0 },
    { name: 'irr', type: 'number' },
    { name: 'tvpi', type: 'number' },
    { name: 'dpi', type: 'number' },
    { name: 'moic', type: 'number' },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'fundraising',
      options: [
        { label: 'Fundraising', value: 'fundraising' },
        { label: 'Active', value: 'active' },
        { label: 'Closed', value: 'closed' },
        { label: 'Winding Down', value: 'winding_down' },
        { label: 'Liquidated', value: 'liquidated' },
      ],
    },
    {
      name: 'fundType',
      type: 'select',
      defaultValue: 'venture',
      options: [
        { label: 'Venture', value: 'venture' },
        { label: 'Growth', value: 'growth' },
        { label: 'Buyout', value: 'buyout' },
        { label: 'Impact', value: 'impact' },
        { label: 'Debt', value: 'debt' },
        { label: 'Hybrid', value: 'hybrid' },
      ],
    },
    { name: 'geography', type: 'text' },
    { name: 'sectors', type: 'json' },
    { name: 'investmentPeriod', type: 'text' },
    { name: 'fundTerm', type: 'text' },
    { name: 'managementFee', type: 'number' },
    { name: 'carriedInterest', type: 'number' },
    { name: 'hurdle', type: 'number' },
    { name: 'benchmark', type: 'text' },
    { name: 'aum', type: 'number' },
    { name: 'dryPowder', type: 'number' },
    { name: 'leverage', type: 'number', defaultValue: 0 },
    { name: 'esg', type: 'checkbox', defaultValue: false },
    { name: 'regulatoryStatus', type: 'text' },
    { name: 'fundAdmin', type: 'text' },
    { name: 'auditor', type: 'text' },
    { name: 'legalCounsel', type: 'text' },
    { name: 'primeBroker', type: 'text' },
    { name: 'manager', type: 'relationship', relationTo: 'users', required: true },
    {
      name: 'legacyPrismaId',
      type: 'text',
      unique: true,
      admin: { position: 'sidebar', readOnly: true },
    },
  ],
}
